# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 5121:5121
  eshop.seq:
  image: datalust/seq:latest
  container_name: eshop-seq
  environment:
    - ACCEPT_EULA=Y
  ports:
    - 5341:5341
    - 8081:80


       
